In [3]:
import pandas as pd

df = pd.read_csv("Dataset/train.csv")

df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
print("Shape:", df.shape)

Shape: (614, 13)

In [5]:
print(df.isnull().sum())

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
# Remove missing values
df = df.dropna()

print("Shape after cleaning:", df.shape)

Shape after cleaning: (480, 13)

In [7]:
# Convert target column

df["Loan_Status"] = df["Loan_Status"].map({"Y": 1, "N": 0})

In [8]:
# One Hot Encoding

df = pd.get_dummies(df)

df.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Loan_ID_LP001003,Loan_ID_LP001005,Loan_ID_LP001006,Loan_ID_LP001008,...,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
1,4583,1508.0,128.0,360.0,1.0,0,True,False,False,False,...,True,False,False,True,False,True,False,True,False,False
2,3000,0.0,66.0,360.0,1.0,1,False,True,False,False,...,False,False,False,True,False,False,True,False,False,True
3,2583,2358.0,120.0,360.0,1.0,1,False,False,True,False,...,False,False,False,False,True,True,False,False,False,True
4,6000,0.0,141.0,360.0,1.0,1,False,False,False,True,...,False,False,False,True,False,True,False,False,False,True
5,5417,4196.0,267.0,360.0,1.0,1,False,False,False,False,...,False,True,False,True,False,False,True,False,False,True

In [9]:
# Save cleaned dataset

df.to_csv("Dataset/cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully